services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\TwentyThree\:
    resource: '../Classes/*'

  B13\TwentyThree\Resource\Rendering\TwentyThreeRenderer:
    public: true

  B13\TwentyThree\EventListener\StartTimeMetadataExtractor:
    tags:
      - name: event.listener
        identifier: 'twentythree-start-time-extractor'
